FROM elasticdump/elasticsearch-dump:latest as base
RUN apt-get update && apt-get install -y vim cron systemd daemon wget
RUN mkdir /temp && wget https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz -P /temp\
    && cd /temp && tar -xvf node_exporter-1.3.1.linux-amd64.tar.gz \
    && mv node_exporter-1.3.1.linux-amd64/node_exporter /usr/local/bin/
RUN service cron start
RUN echo "[Unit]\
\nDescription=Node Exporter\
\nAfter=network.target\
\n\ 
\n[Service]\
\nUser=root\
\nGroup=root\
\nType=simple\
\nExecStart=/usr/local/bin/node_exporter\
\n\ 
\n[Install]\
\nWantedBy=multi-user.target" > /etc/systemd/system/node_exporter.service
