name: Unified Docker Workflow
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - '**.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - '**.md'
  release:
    types: [published, edited]

env:
  DATAHUB_GMS_IMAGE: 'linkedin/datahub-gms'
  DATAHUB_FRONTEND_IMAGE: 'linkedin/datahub-frontend-react'
  DATAHUB_MAE_CONSUMER_IMAGE: 'linkedin/datahub-mae-consumer'
  DATAHUB_MCE_CONSUMER_IMAGE: 'linkedin/datahub-mce-consumer'
  DATAHUB_KAFKA_SETUP_IMAGE: 'linkedin/datahub-kafka-setup'
  DATAHUB_ELASTIC_SETUP_IMAGE: 'linkedin/datahub-elasticsearch-setup'
  DATAHUB_MYSQL_SETUP_IMAGE: 'acryldata/datahub-mysql-setup'
  DATAHUB_UPGRADE_IMAGE: 'acryldata/datahub-upgrade'
  

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
      unique_tag: ${{ steps.tag.outputs.unique_tag }}
      publish: ${{ steps.publish.outputs.publish }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compute Tag
        id: tag
        run: |
          echo "GITHUB_REF: $GITHUB_REF"
          SHORT_SHA=$(git rev-parse --short "$GITHUB_SHA")
          TAG=$(echo ${GITHUB_REF} | sed -e "s,refs/heads/master,head\,${SHORT_SHA},g" -e 's,refs/tags/,,g' -e 's,refs/pull/\([0-9]*\).*,pr\1,g')
          UNIQUE_TAG=$(echo ${GITHUB_REF} | sed -e "s,refs/heads/master,${SHORT_SHA},g" -e 's,refs/tags/,,g' -e 's,refs/pull/\([0-9]*\).*,pr\1,g')
          echo "tag=$TAG"
          echo "unique_tag=$UNIQUE_TAG"
          echo "::set-output name=tag::$TAG"
          echo "::set-output name=unique_tag::$UNIQUE_TAG"
      - name: Check whether publishing enabled
        id: publish
        env:
          ENABLE_PUBLISH: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "Enable publish: ${{ env.ENABLE_PUBLISH != '' }}"
          echo "::set-output name=publish::${{ env.ENABLE_PUBLISH != '' }}"
  kafka_setup_build:
    name: Build and Push DataHub Kafka Setup Docker Image
    runs-on: ubuntu-latest
    needs: setup
    outputs:
      image_tag: ${{ steps.docker_meta.outputs.tags }}
      image_name: ${{ env.DATAHUB_KAFKA_SETUP_IMAGE }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ env.DATAHUB_KAFKA_SETUP_IMAGE }}
          # add git short SHA as Docker tag
          tag-custom: ${{ needs.setup.outputs.tag }}
          tag-custom-only: true
      - name: Build and Load image for testing (if not publishing)
        uses: docker/build-push-action@v2
        if: ${{ needs.setup.outputs.publish != 'true' }}
        with:
          context: ./docker/kafka-setup
          file: ./docker/kafka-setup/Dockerfile
          platforms: linux/amd64
          tags: ${{ steps.docker_meta.outputs.tags }}
          load: true
          push: false
      - name: Upload image locally for testing (if not publishing)
        uses: ishworkh/docker-image-artifact-upload@v1
        if: ${{ needs.setup.outputs.publish != 'true' }}
        with:
          image: ${{ steps.docker_meta.outputs.tags }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        if: ${{ needs.setup.outputs.publish == 'true' }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        if: ${{ needs.setup.outputs.publish == 'true' }}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        if: ${{ needs.setup.outputs.publish == 'true' }}
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push MultiPlatform image
        uses: docker/build-push-action@v2
        if: ${{ needs.setup.outputs.publish == 'true' }}
        with:
          context: ./docker/kafka-setup
          file: ./docker/kafka-setup/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.docker_meta.outputs.tags }}
          push: true
  mysql_setup_build:
    name: Build and Push DataHub MySQL Setup Docker Image
    runs-on: ubuntu-latest
    needs: setup
    outputs:
      image_tag: ${{ steps.docker_meta.outputs.tags }}
      image_name: ${{ env.DATAHUB_MYSQL_SETUP_IMAGE }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ env.DATAHUB_MYSQL_SETUP_IMAGE }}
          # add git short SHA as Docker tag
          tag-custom: ${{ needs.setup.outputs.tag }}
          tag-custom-only: true
      - name: Build and Load image for testing (if not publishing)
        uses: docker/build-push-action@v2
        if: ${{ needs.setup.outputs.publish != 'true' }}
        with:
          context: .
          file: ./docker/mysql-setup/Dockerfile
          platforms: linux/amd64
          tags: ${{ steps.docker_meta.outputs.tags }}
          load: true
          push: false
      - name: Upload image locally for testing (if not publishing)
        uses: ishworkh/docker-image-artifact-upload@v1
        if: ${{ needs.setup.outputs.publish != 'true' }}        
        with:
          image: ${{ steps.docker_meta.outputs.tags }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        if: ${{ needs.setup.outputs.publish == 'true' }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        if: ${{ needs.setup.outputs.publish == 'true' }}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        if: ${{ needs.setup.outputs.publish == 'true' }}
        with:
          username: ${{ secrets.ACRYL_DOCKER_USERNAME }}
          password: ${{ secrets.ACRYL_DOCKER_PASSWORD }}
      - name: Build and Push MultiPlatform image
        uses: docker/build-push-action@v2
        if: ${{ needs.setup.outputs.publish == 'true' }}
        with:
          context: .
          file: ./docker/mysql-setup/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.docker_meta.outputs.tags }}
          push: true
  elasticsearch_setup_build:
    name: Build and Push DataHub Elasticsearch Setup Docker Image
    runs-on: ubuntu-latest
    needs: setup
    outputs:
      image_tag: ${{ steps.docker_meta.outputs.tags }}
      image_name: ${{ env.DATAHUB_ELASTIC_SETUP_IMAGE }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ env.DATAHUB_ELASTIC_SETUP_IMAGE }}
          # add git short SHA as Docker tag
          tag-custom: ${{ needs.setup.outputs.tag }}
          tag-custom-only: true
      - name: Build and Load image for testing (if not publishing)
        uses: docker/build-push-action@v2
        if: ${{ needs.setup.outputs.publish != 'true' }}
        with:
          context: .
          file: ./docker/elasticsearch-setup/Dockerfile
          platforms: linux/amd64
          tags: ${{ steps.docker_meta.outputs.tags }}
          load: true
          push: false
      - name: Upload image locally for testing (if not publishing)
        uses: ishworkh/docker-image-artifact-upload@v1
        if: ${{ needs.setup.outputs.publish != 'true' }}
        with:
          image: ${{ steps.docker_meta.outputs.tags }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        if: ${{ needs.setup.outputs.publish == 'true' }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        if: ${{ needs.setup.outputs.publish == 'true' }}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        if: ${{ needs.setup.outputs.publish == 'true' }}
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push MultiPlatform image
        uses: docker/build-push-action@v2
        if: ${{ needs.setup.outputs.publish == 'true' }}
        with:
          context: .
          file: ./docker/elasticsearch-setup/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.docker_meta.outputs.tags }}
          push: true
